### ISSUE TITLE
java.lang.NoSuchFieldError: animationLength

### ISSUE THREAD

**Issue by babebridou** [MSandro/sky_fabrication3#36] opened 2022-11-03 17:29 UTC
Hey, the game crashes upon joining an existing world.

From what I can tell GeckoLib crashes every time a MythicMount beast spawns nearby. I tried to use NBTExplorer to remove all the dragons and geckotoas but in my particular world, it doesn't take long for a new Dragon to spawn and crash the game so I can only play for a few seconds.

Here's the most recent crash log, after cleaning up all mythicmount entities with NBTExplorer

[crash-2022-11-03_18.02.46-client.txt](https://github.com/MSandro/sky_fabrication3/files/9931533/crash-2022-11-03_18.02.46-client.txt)

And here's the first crash log I experienced.

[crash-2022-11-01_21.22.52-client.txt](https://github.com/MSandro/sky_fabrication3/files/9931622/crash-2022-11-01_21.22.52-client.txt)

For what it's worth, the modpack and this world worked fine when I last played it on october 15. It also seems to work fine on a brand new world, though I haven't tried to spawn a mythic mount there yet.

**Comment by MSandro** [comment] 2022-11-12 23:12
removing MythicMount should fix the issue.
It will be removed in the next release

**Comment by MSandro** [comment] 2022-11-14 05:52
duplicate of #35

**Closed by MSandro** 2022-11-14 05:52 UTC
